apiVersion: v1
kind: ReplicationController
metadata:
  name: basic-svc-repl-ctrl
spec:
  replicas: 3
  selector:
    app: basic-svc-app
  template:
    metadata:
      labels:
        app: basic-svc-app
    spec:
      containers:
      - name: mysvc
        image: mitchd/basic-svc
        ports:
        - containerPort: 8083
